general:
  prefix: "&bLEVEL: "
  prefixError: "&f&c "
  prefixInfo: "&f&b "
  
levels:
  initialExp: 100              # Expérience pour passer du niveau 1 au 2
  expIncrementPercent: 30      # Pourcentage d'augmentation par niveau
  fish_exp: 10                 # Exp gagné avec la pêche
  breed_exp: 15
  break_blocks:
    - "*_LOG": 1
    #Mineraits
    - "COAL_ORE": 0
    - "DEEPSLATE_COAL_ORE": 0
    - "IRON_ORE": 0
    - "DEEPSLATE_IRON_ORE": 0
    - "COPPER_ORE": 0
    - "DEEPSLATE_COPPER_ORE": 0
    - "GOLD_ORE": 0
    - "DEEPSLATE_GOLD_ORE": 0
    - "REDSTONE_ORE": 0
    - "DEEPSLATE_REDSTONE_ORE": 0
    - "EMERALD_ORE": 0
    - "DEEPSLATE_EMERALD_ORE": 0
    - "LAPIS_ORE": 0
    - "DEEPSLATE_LAPIS_ORE": 0
    - "DIAMOND_ORE": 0
    - "DEEPSLATE_DIAMOND_ORE": 0
    - "NETHER_GOLD_ORE": 0
    - "NETHER_QUARTZ_ORE": 0
    - "ANCIENT_DEBRIS": 0
    #Agricultures
    - "WHEAT": 0
      "age": 7
    - "CARROTS": 0
      "age": 7
    - "POTATOES": 0
      "age": 7
    - "BEETROOTS": 0
      "age": 3
    - "PUMPKIN": 0
    - "MELON": 0
    - "SUGAR_CANE": 0

  # Expérience pour tuer des mobs
  mob_kill_exp:
    - "zombie": 20
    - "skeleton": 15
    - "creeper": 25
    - "enderman": 50

# Display formats showing player levels
tablist-format: "&f[lvl %level_level_{name}%] &7{name}"
nametag-format: "&f[lvl %level_level_{name}%] &7{name}"
